language: java
jdk:
  - oraclejdk7
before_install:
  - cp travis/settings.xml ~/.m2/settings.xml
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: ls -la /home/travis/build/ISA-tools/ISAcreator/src/main/resources/Configurations/isaconfig-default_v2015-07-02