language: java
jdk:
  - oraclejdk8
before_install:
  - cp travis/settings.xml ~/.m2/settings.xml
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: ./compile.sh
after_success:
  - ./run_tests.sh