language: java
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://repository-master.mulesoft.org/nexus/content/groups/public/|g' ~/.m2/settings.xml
script: mvn clean verify